ToDolist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<id>\d{0,50})/$', views.details, name='details'),
    url(r'^add', views.add, name='add'),
    url(r'^edit/(?P<id>\w{0,50})/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>\w{0,50})/$', views.delete, name='delete'),
    url(r'^finished/(?P<id>\w{0,50})/$', views.finished, name='finished'),
]

ToDolist_for_RG/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authuser.urls', namespace='auth')),
    url(r'^todolist/', include('ToDolist.urls')),
    url(r'^', include('ToDolist.urls', namespace='todolist')),

    # url(r'^task/', include('task.urls', namespace='task')),
    # url(r'^start/', include('ToDolist.urls')),
    # url(r'^article/', include('article.urls', namespace='article')),

]

authuser/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),  #
    url(r'^logout/$', views.logout, name='logout'), #
    url(r'^register/$', views.register, name='register'), #
    ]

ToDolist/models.py
from datetime import datetime, date
import time

from django.db import models


# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_at = models.DateTimeField(default=datetime.now(), blank=True)
    finished_at = models.DateTimeField(default=datetime.now(), blank=True)
    finished = models.BooleanField(default=False)
    priority = models.IntegerField(default=0)
    deadline = models.DateField(default=date.today(), blank=True)

    def __str__(self): #this is to return the name of the object.
        return self.title

authuser/models.py
from django.db import models

# Create your models here.

ToDolist/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User
from django.db.models import DateField, DateTimeField
from django.forms import SelectDateWidget, TextInput, Textarea, DateTimeInput

from ToDolist.models import Todo


class TodoForm(forms.ModelForm):

    tododate = forms.DateTimeField(widget=SelectDateWidget())

    class Meta:

        model = Todo
        fields = ["title", "content", "tododate"]

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget = TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Baslik',
            'id': 'title'})
        self.fields['content'].widget = Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Yapilacak'})


# class TodoListForm(forms.ModelForm):
#     class Meta:
#         model = Todo
#         fields = ['title', 'text', 'deadline', 'finished', 'finished_at', 'priority', 'created_at']#'__all__'

ToDolist/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.http import Http404
from django.http import HttpResponse
from datetime import datetime, date
from django.utils.timezone import get_current_timezone
#from .forms import TodoListForm

# Create your views here.


def index(request):
    todos = Todo.objects.filter(finished=False)
    finishedtodos = Todo.objects.filter(finished=True)
    context = {
        'todos': todos,
        'finishedtodos': finishedtodos,
    }
    return render(request, 'todolist/index.html', context)


def details(request, id):
    todo = Todo.objects.get(id=id)
    context = {
        'todo': todo,
    }
    return render(request, 'todolist/details.html', context)


def add(request):
    if(request.method == 'POST'):
        title = request.POST['title']
        text = request.POST['text']
        priority = request.POST['priority']
        deadlinea = request.POST['deadlinea']
        todo = Todo(title=title, text=text, priority=priority, deadline=deadlinea)
        todo.save()

        return redirect('/')
    else:
        return render(request, 'todolist/add.html')


def edit(request, id):
    todo = Todo.objects.get(id=id)
    context = {
        'todo': todo,
    }

    if request.method == 'POST':
        todo = Todo.objects.get(id=id)
        text = request.POST['text']
        priority = request.POST['priority']
        todo = Todo.objects.filter(id=id).update(text=text, priority=priority)
        return redirect('/')
    else:
        return render(request, 'todolist/edit.html', context)


def delete(request, id):
    try:todo = Todo.objects.get(id=id)
    except Exception:
        raise Http404
    if todo:
        todo.delete()
    return redirect('/')


def finished(request, id):
    try:
        todo = Todo.objects.get(id=id)
    except Exception:
        raise Http404
    if todo:
        if todo.finished == False:
            todo = Todo.objects.filter(id=id).update(finished=True, finished_at=datetime.now())
        else:
            todo = Todo.objects.filter(id=id).update(finished=False)
    return redirect('/')

authuser/views.py
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.template.context_processors import csrf

# Create your views here.


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '') # Получить из пост запроса юзернейм
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password) # Отправляю логин и пароль в auth
        if user is not None:
            auth.login(request, user) # Авторизация найденного пользователя
            return redirect('/')
        else:
            args['login_error'] = 'Пользователь не найден'
            return render_to_response('authuser/login.html', args)
    else:
        return render_to_response('authuser/login.html', args)


def logout(request):
    auth.logout(request) # Делогон пользователя
    return redirect('/')


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm() # Создание элемента словаря и передаеться в него форма из коробки
    if request.POST:
        newuser_form = UserCreationForm(request.POST) # созд новую форму после
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(
                username=newuser_form.cleaned_data['username'],
                password=newuser_form.cleaned_data['password2'],)
            auth.login(request, newuser)
            return redirect('/')
        else:
            args['form'] = newuser_form
    return render_to_response('authuser/register.html', args)

templates/todolist/add.html
{% extends 'todolist/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block add %}
    <form action="{% url "todolist:add" %}" method="post">
    {% csrf_token %}
    <div class="col-lg-8">
        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <div class="input-group-addon">Title task</div>
            <input type="text" class="form-control" id="title" name="title" placeholder="Title" />
        </div>
        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <div class="input-group-addon">Text task</div>
            <input type="text" class="form-control" id="text" name="text" placeholder="Text" />
        </div>
        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
            <div class="input-group-addon">DeadLine task</div>
            <input type="date" class="form-control" name="deadlinea" id="deadlinea example-datetime-local-input" placeholder="Chose date" />
        </div>
    <fieldset class="form-group">
    <legend>Importance:</legend>
    <div class="form-check">
      <label class="form-check-label">
        <input type="radio" class="form-check-input" name="priority" id="optionsRadios1" value="1" {% if not todo.priority or todo.priority == 1 %} checked {% endif %}>
        <span class="btn btn-danger btn-xs">Urgent</span>
      </label>
      <label class="form-check-label">
        <input type="radio" class="form-check-input" name="priority" id="optionsRadios1" value="2" {% if todo.priority == 2 %} checked {% endif %}>
        <span class="btn btn-warning btn-xs">Caution</span>
      </label>
      <label class="form-check-label">
        <input type="radio" class="form-check-input" name="priority" id="optionsRadios1" value="3" {% if todo.priority == 3 %} checked {% endif %}>
        <span class="btn btn-success btn-xs">Smooth</span>
      </label>
    </div>
    </fieldset>
    </div>

        <br><br>
        <input type="submit" class="btn btn-primary" value="Submit"/>
    </form>
    <br>
    <a href="{% url "todolist:index" %}">Go Back</a>

{% endblock %}

templates/todolist/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="MorpheusFR">
    <link rel="icon" href="{% static "img/list.png" %}">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "/css/bootstrap-theme.css" %}" rel="stylesheet">
    <script src="https://cdn.jsdeliver.net/g/jquery@1.9.1,bootstrap@3.3.6"></script>
    <script src="{% static "/js/vendor/jquery.js" %}"></script>
    <script src="{% static "/js/bootstrap.min.js" %}"></script>
    <!-- Подключения скрипта control-modal.min.js к странице -->
    <script src="js/control-modal.min.js"></script>


  </head>
<body background="{% static "img/blur1.jpg" %}" >
{#<nav class="navbar navbar-inverse navbar-fixed-top">#}
{#  <div class="container">#}
{#    <div class="navbar-header">#}
{#      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">#}
{#        <span class="sr-only">Toggle navigation</span>#}
{#        <span class="icon-bar"></span>#}
{#      </button>#}
{#        <nav class="navbar navbar-light bg-faded">#}
{#          <a class="navbar-brand" href="#">#}
{#            <img src="{% static "img/list.png" %}" width="18" height="18" class="d-inline-block align-top" alt=""></a>#}
{#            <a class="navbar-brand" href="/">Single TODO list for RG</a>#}
{#            </nav>#}
{#    </div>#}
{#    <div id="navbar" class="collapse navbar-collapse">#}
{#      <ul class="nav navbar-nav">#}
{#        <li class="active"><a href="#">Home</a></li>#}
{#          <li><a href="#">About</a></li>#}
{#          <li><a href="#">Contact</a></li>#}
{#          <li> ___________________________ </li>#}
{#          {% if username %}#}
{#            <li><a href="{% url "auth:logout" %}" class="navbar-link pull-right">Logout user "{{ username }}"</a></li>#}
{#          {% else %}#}
{#            <li><a href="{% url "auth:login" %}" class="navbar-link pull-right">Sing up</a></li>#}
{#          {% endif %}#}
{#      </ul>#}
{#    </div>#}
{#  </div>#}
{#</nav>#}
 <div class="container">
    <div class="">
    <header id="main_header">
      <h1>TodoList</h1>
        <a href="{% url "todolist:add" %}" class="btn btn-default">Add Todo</a>
        <hr>
    </header>





    {% block index%}{% endblock %}
    {% block add %}{% endblock %}
    {% block details %}{% endblock %}
    {% block edit %}{% endblock %}



{#    <div class=""></div>#}
{#      <div class="card" style="width: 50rem ; background-color: #9acfea">#}
{#        <div class="card-block">#}
{#          <h1 class="card-title">Welcome to the Prototype App</h1>#}
{#          <h3 class="card-text">This is the home page for the TODO application.</h3>#}
{#          <a href="{% url "auth:login" %}" class="btn btn-primary">Sing up</a>#}
{#        </div>#}
{#        <div class=""></div>#}
{#      </div>{% block login %}{% endblock %}#}
{#        #}



    </div>
  </div>

</body>
</html>

templates/todolist/details.html
{% extends 'todolist/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block details %}
    <a href="{% url "todolist:index" %}"><< Go Back</a>
    <br>
    <h1>{{todo.title}}</h1>
    <p>{{todo.text}}</p>
    <br>
    Created on {{todo.created_at}}
{% endblock %}

templates/todolist/edit.html
{% extends 'todolist/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block edit %}
    <h2>{{todo.title}}</h2>
    <p>{{todo.text}}</p>
    <font color="red"> Deadline: {{todo.finished_at}}</font>
<form action="{% url 'todolist:edit' todo.id %}" method="POST">
    {% csrf_token %}

    <br>
    <br>
    <label for="text">Modify content:</label><br />
    <textarea name="text" id="text"></textarea>
    <br><br>
    <label>Importance: </label>
    <label class="checkbox-inline">
      <input type="radio" name="priority" value='1' {% if not todo.priority or todo.priority == 1 %} checked {% endif %}><span class="btn btn-danger btn-xs">Urgent</span>
    </label>
    <label class="checkbox-inline">
      <input type="radio" name="priority" value="2" {% if todo.priority == 2 %} checked {% endif %}><span class="btn btn-warning btn-xs">Caution</span>
    </label>
    <label class="checkbox-inline">
      <input type="radio" name="priority" value="3" {% if todo.priority == 3 %} checked {% endif %}><span class="btn btn-success btn-xs">Smooth</span>
    </label>
    <br><br>
    <input type="submit" value="Submit" />
</form>
    <br>
    <a href="{% url "todolist:index" %}">Go Back</a>
{% endblock %}

templates/todolist/index.html
{% extends 'todolist/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block index %}
<div class="todolist">
    <h2>Todo Items:</h2>




{#    <!--<ul>-->#}
{#        <!--{% for todo in todos %}-->#}
{#        <!--<li>-->#}
{#            <!--<a href="/todos/details/{{todo.id}}">{{todo.title}}</a>: {{todo.text}}-->#}
{#            <!--&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->#}
{#            <!--<a class='edit' href="/todos/edit/{{todo.id}}">|Edit</a>-->#}
{#            <!--<a class='delete' href="/todos/delete/{{todo.id}}">|Delete</a>-->#}
{#            <!--<a class='finished' href="/todos/finished/{{todo.id}}">|Finished</a>-->#}
{#            <!--{% if todo.priority == 1 %}-->#}
{#               <!--<font color="red" class="importance">&#45;&#45;Urgent</font>-->#}
{#            <!--{% endif %}-->#}
{#            <!--{% if todo.priority == 2 %}-->#}
{#               <!--<font color="blue" class="importance">&#45;&#45;Caution</font>-->#}
{#            <!--{% endif %}-->#}
{#            <!--{% if todo.priority == 3 %}-->#}
{#               <!--<font color="black" class="importance">&#45;&#45;Smooth</font>-->#}
{#            <!--{% endif %}-->#}
{#            <!--<br>-->#}
{#            <!--<font color="red" class="ddl_tag">Deadline:{{todo.deadline}}</font>-->#}
{#        <!--</li>-->#}
{#        <!--{% endfor %}-->#}
{#    <!--</ul>-->#}
    <div class="alert alert-info" role="alert">
      <strong>Heads up!</strong> This alert needs your attention, but it's not super important.

    <table width="1000" border="0">
        <tr>
            <th>Title</th>
            <th>content</th>
            <th>Operation</th>
            <th>Status</th>
            <th>Deadline</th>

        </tr>
        {% for todo in todos %}
        <tr>
            <th><a class="btn btn-primary" href="/todolist/details/{{todo.id}}/" role="button">{{todo.title}}</a></th>
            <th>{{todo.text}}</th>
            <th width="190px">
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="/todolist/edit/{{todo.id}}/" type="button" class="btn btn-secondary btn-info">Edit</a>
                  <a href="/todolist/delete/{{todo.id}}/" type="button" class="btn btn-secondary btn-danger">Delite</a>
                  <a href="/todolist/finished/{{todo.id}}/" type="button" class="btn btn-secondary btn-success">Finished</a>

                </div>
            </th>
            <th>
                {% if todo.priority == 1 %}
                   <font color="red" class="importance">Urgent</font>
                {% endif %}
                {% if todo.priority == 2 %}
                   <font color="blue" class="importance">Caution</font>
                {% endif %}
                {% if todo.priority == 3 %}
                   <font color="green" class="importance">Smooth</font>
                {% endif %}
            </th>
            <th><font color="red" class="ddl_tag">{{todo.deadline}}</font></th>
        </tr>
        {% endfor %}
    </table>
    </div>
    <br><hr>
</div>

<div class="finishedlist">
    <h2>Finished Items:</h2>
    <!--<ul>-->
        <!--{% for todo in finishedtodos %}-->
        <!--<li>-->
        <!--<a href="/todos/details/{{todo.id}}">{{todo.title}}</a>: {{todo.text}}-->
        <!--<a class='edit' href="/todos/edit/{{todo.id}}">|Edit</a>-->
        <!--<a class='delete' href="/todos/delete/{{todo.id}}">|Delete</a>-->
        <!--<a class='finished' href="/todos/finished/{{todo.id}}">|Unfinished</a>-->
        <!--<br>-->
        <!--<font color="red" class="ddl_tag">Finished at: {{todo.finished_at}}</font>-->
        <!--</li>-->
        <!--{% endfor %}-->
    <!--</ul>-->
    <table width="800" border="1">
        <thead>
            <tr>
                <th>Title</th>
                <th>content</th>
                <th>Operation</th>
                <th>Finished Date</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in finishedtodos %}
            <tr>
                <th>
                    <a href="/todos/details/{{todo.id}}">{{todo.title}}</a>
                </th>
                <th>{{todo.text}}</th>
                <th>
                    <a class='edit' href="/todos/edit/{{todo.id}}">|Edit</a>
                    <a class='delete' href="/todos/delete/{{todo.id}}">|Delete</a>
                    <a class='finished' href="/todos/finished/{{todo.id}}">|Unfinished</a>
                </th>
                <th>
                    <font color="red" class="ddl_tag">{{todo.finished_at}}</font>
                </th>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
<!--<script type="text/javascript">-->
    <!--$(function(){-->
        <!--var $table=$('table');-->
        <!--var currentPage=0;-->
        <!--var pageSize=2;-->
        <!--$table.bind('paging',function(){-->
            <!--$tabel.find('tbody tr').hide.slice(currentPage*pageSize,(currentPage+1)*pageSize).show();-->
        <!--});-->
    <!--var sumRows=$table.find('tbody tr').length;-->
    <!--var sumPages=Math.ceil(sumRows/pageSize);-->
    <!--var $pager=$('<div class="page"></div>');-->
    <!--for(var pageIndex=0;pageIndex<sumPages;pageIndex++){-->
        <!--$('<a href="#"><span>'+(pageIndex+1)+'</span></a>').bind("click",{"newPage":pageIndex}, function(event){-->
            <!--currentPage=event.data["newPage"];-->
            <!--$table.trigger("paging");-->
        <!--}).appendTo($pager);-->
        <!--$pager.append(" ");-->
    <!--}-->
    <!--$pager.insertAfter($table);-->
    <!--$table.trigger("paging");-->
    <!--});-->
<!--</script>-->

    <div class="alert alert-success" role="alert">
  <strong>Well done!</strong> You successfully read this important alert message.
</div>
<div class="alert alert-info" role="alert">
  <strong>Heads up!</strong> This alert needs your attention, but it's not super important.
</div>
<div class="alert alert-warning" role="alert">
  <strong>Warning!</strong> Better check yourself, you're not looking too good.
</div>
<div class="alert alert-danger" role="alert">
  <strong>Oh snap!</strong> Change a few things up and try submitting again.
</div>



{% endblock %}
{% comment %}
{% include 'todolist/partials/footer.html' %}
{% endcomment %}

templates/todolist/partials/footer.html
    </div>
  </body>
</html>

templates/todolist/partials/header.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>TodoList</title>
</head>
<body>